delete from transactionDetails
delete from transactions
delete from category
delete from tableTransaction
delete from TableNumber
delete from substitues
delete from itemKit
delete from itemKitdetails
delete from suspended
delete from void_all
delete from log
delete from login_Time
delete from shiftclose
delete from looseChange
delete from zReport
delete from zReport_details
delete from mini_Zreport
delete from statisticReport
delete from statisticReport_details
delete from xReport
delete from xReport_details
delete from customer
delete from displayMoneyBar
delete from randomImg
delete from repair
delete from shiftManagement
delete from zReportShift
delete from zReportShift_details

